# Generated by Django 2.2.5 on 2019-10-20 15:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Описание статьи'),
        ),
    ]
