# Generated by Django 2.2.5 on 2019-10-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191021_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_pdf',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Статья в pdf'),
        ),
    ]
