# Generated by Django 2.2.5 on 2019-10-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_article_pdf'),
        ('personal_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='articles',
            field=models.ManyToManyField(blank=True, to='articles.Article'),
        ),
    ]
