# Generated by Django 2.2.5 on 2019-10-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HandbookNode',
        ),
    ]
