# Generated by Django 2.2.5 on 2019-10-22 08:37

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0004_auto_20191018_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handbook',
            options={'verbose_name': 'в справочник', 'verbose_name_plural': 'Справочник'},
        ),
        migrations.AlterField(
            model_name='handbook',
            name='group',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='handbook',
            name='is_link',
            field=models.BooleanField(default=False, verbose_name='Это ссылка.'),
        ),
        migrations.AlterField(
            model_name='handbook',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='handbook',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='handbook.Handbook', verbose_name='Родитель'),
        ),
    ]
