# Generated by Django 2.2.5 on 2020-02-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryAggregateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('country_long', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.DateField(blank=True, db_index=True, null=True)),
                ('imp_sum_cost', models.BigIntegerField(blank=True, null=True, verbose_name='Импорт - суммарная стоимость')),
                ('exp_sum_cost', models.BigIntegerField(blank=True, null=True, verbose_name='Экспорт - суммарная стоимость')),
                ('imp_sum_weight', models.BigIntegerField(blank=True, null=True, verbose_name='Импорт - суммарный вес')),
                ('exp_sum_weight', models.BigIntegerField(blank=True, null=True, verbose_name='Экспорт - суммарный вес')),
            ],
        ),
        migrations.CreateModel(
            name='CountryHandbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticAggregateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True)),
                ('imp_sum_cost', models.BigIntegerField(verbose_name='Импорт - суммарная стоимость')),
                ('exp_sum_cost', models.BigIntegerField(verbose_name='Экспорт - суммарная стоимость')),
                ('imp_sum_weight', models.BigIntegerField(verbose_name='Импорт - суммарный вес')),
                ('exp_sum_weight', models.BigIntegerField(verbose_name='Экспорт - суммарный вес')),
                ('imp_sum_unique_countries', models.BigIntegerField(verbose_name='Импорт - Количество вовлеченных стран')),
                ('exp_sum_unique_countries', models.BigIntegerField(verbose_name='Экспорт - Количество вовлеченных стран')),
                ('imp_tnved_by_max_cost', models.BigIntegerField(verbose_name='Импорт - Код тнвэд имеющий максимальную стоимость')),
                ('exp_tnved_by_max_cost', models.BigIntegerField(verbose_name='Экспорт - Код тнвэд имеющий максимальную стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('napr', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('period', models.DateField(blank=True, db_index=True, null=True)),
                ('strana', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('tnved', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('tnved_two', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('tnved_four', models.CharField(blank=True, db_index=True, max_length=4, null=True)),
                ('tnved_six', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('tnved_eight', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('edizm', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('stoim', models.DecimalField(blank=True, decimal_places=0, max_digits=22, null=True)),
                ('netto', models.DecimalField(blank=True, decimal_places=0, max_digits=22, null=True)),
                ('kol', models.DecimalField(blank=True, decimal_places=0, max_digits=22, null=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('region_s', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TnvedHandbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnved', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
