# Generated by Django 2.2.5 on 2020-03-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_regionhandbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryhandbook',
            name='continent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
