# Generated by Django 2.2.5 on 2019-10-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20191021_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
