# Generated by Django 2.2.5 on 2019-10-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20191021_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=87, null=True, verbose_name='Описание'),
        ),
    ]
