# Generated by Django 2.2.5 on 2019-12-05 11:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20191205_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
