# Generated by Django 2.2.5 on 2019-12-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20191205_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cost',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Цена'),
        ),
    ]
