# Generated by Django 2.2.5 on 2020-01-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20200120_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fax', models.CharField(blank=True, max_length=255, null=True, verbose_name='Факс')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('INN', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН')),
                ('OGRN', models.CharField(blank=True, max_length=255, null=True, verbose_name='ОГРН')),
                ('KPP', models.CharField(blank=True, max_length=255, null=True, verbose_name='КПП')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactsOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('map_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка карты')),
            ],
        ),
        migrations.CreateModel(
            name='ContactsPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='ContactsOfficeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_link', models.ImageField(upload_to='')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.ContactsOffice')),
            ],
        ),
    ]
