# Generated by Django 2.2.5 on 2020-01-20 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_contacts_contactsoffice_contactsofficeimage_contactsphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsphone',
            name='number_link',
            field=models.CharField(default='', max_length=255, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='contactsoffice',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='index.Contacts'),
        ),
        migrations.AlterField(
            model_name='contactsofficeimage',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='index.ContactsOffice'),
        ),
        migrations.AlterField(
            model_name='contactsphone',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='index.Contacts'),
        ),
    ]
