# Generated by Django 2.2.5 on 2020-01-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20200120_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='fax_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Факс ссылка'),
        ),
    ]
