# Generated by Django 2.2.5 on 2020-01-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_contacts_fax_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsofficeimage',
            old_name='img_link',
            new_name='img',
        ),
    ]
