# Generated by Django 2.2.5 on 2020-01-20 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20200120_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='index.Contacts')),
            ],
        ),
    ]
