# Generated by Django 2.2.5 on 2020-02-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_contactsteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='contactsoffice',
            options={'verbose_name': 'Офис', 'verbose_name_plural': 'Офисы'},
        ),
        migrations.AlterModelOptions(
            name='contactsofficeimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='contactsphone',
            options={'verbose_name': 'Телефонный номер', 'verbose_name_plural': 'Телефонные номера'},
        ),
        migrations.AlterModelOptions(
            name='contactsteam',
            options={'verbose_name': 'Член команды', 'verbose_name_plural': 'Члены команды'},
        ),
        migrations.AlterField(
            model_name='contactsofficeimage',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
