# Generated by Django 2.2.5 on 2019-10-07 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_cabinet', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal_cabinet.Client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_frequency', models.CharField(choices=[('MU', 'Ежемесячное обновление'), ('QU', 'Ежеквартальное обновление')], max_length=2, verbose_name='частота обновления')),
                ('duration', models.CharField(choices=[('OM', 'На один месяц'), ('OQ', 'На один квартал'), ('HY', 'На пол года'), ('OY', 'На один год')], max_length=2, verbose_name='подписка')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='стоимость')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.Research', verbose_name='Исследования')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal_cabinet.Client', verbose_name='Клиент')),
                ('research', models.ManyToManyField(blank=True, to='products.Research', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
