# Generated by Django 2.2.5 on 2019-10-30 13:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191030_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='INN',
            field=models.IntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='order',
            name='KPP',
            field=models.IntegerField(blank=True, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='firm_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название фирмы'),
        ),
        migrations.AddField(
            model_name='order',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Мобильный телефон'),
        ),
    ]
