# Generated by Django 2.2.5 on 2019-11-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191103_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'get_latest_by': 'id', 'verbose_name': 'Исследование', 'verbose_name_plural': 'Исследования'},
        ),
    ]
