# Generated by Django 2.2.5 on 2020-05-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191208_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='legal_adress',
            field=models.CharField(blank=True, max_length=100, verbose_name='Юридический адрес'),
        ),
    ]
