# Generated by Django 2.2.5 on 2019-10-07 16:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('target', models.TextField(blank=True, null=True, verbose_name='Цель исследования')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание исследования')),
                ('data_update', models.TextField(blank=True, null=True, verbose_name='Обновление данных')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('demo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Демо файл')),
                ('contents', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Оглавление')),
                ('using_methods', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Используемые методы')),
                ('data_sources', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Источники данных')),
                ('research_type', models.CharField(choices=[('industry', 'Отраслевое'), ('export', 'Экспорт'), ('import', 'Импорт')], max_length=10, verbose_name='Тип исследования')),
                ('OM_cost', models.IntegerField(verbose_name='цена за месяц')),
                ('OQ_cost', models.IntegerField(blank=True, null=True, verbose_name='цена за квартал')),
                ('HY_cost', models.IntegerField(blank=True, null=True, verbose_name='цена за полгода')),
                ('OY_cost', models.IntegerField(blank=True, null=True, verbose_name='цена за год')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('seo_title', models.TextField(blank=True, max_length=200, null=True)),
                ('seo_description', models.TextField(blank=True, max_length=200, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': ' Исследование',
                'verbose_name_plural': 'Исследования',
            },
        ),
    ]
