# Generated by Django 2.2.5 on 2019-10-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='research',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='research',
            name='seo_title',
        ),
    ]
