# Generated by Django 2.2.5 on 2019-10-23 14:41

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191023_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='research',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Category', verbose_name='Категория'),
        ),
    ]
