# Generated by Django 2.2.5 on 2019-10-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20191023_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualResearchFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('contact_details', models.CharField(max_length=200, verbose_name='Контактные данные')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
            ],
            options={
                'verbose_name': 'Исследование на заказ',
                'verbose_name_plural': 'Исследования на заказ',
            },
        ),
    ]
