# Generated by Django 2.2.5 on 2019-10-29 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_individualresearchfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='HY_cost',
        ),
        migrations.RemoveField(
            model_name='research',
            name='OM_cost',
        ),
        migrations.RemoveField(
            model_name='research',
            name='OQ_cost',
        ),
        migrations.RemoveField(
            model_name='research',
            name='OY_cost',
        ),
        migrations.AddField(
            model_name='research',
            name='M_HY_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ежемесячное обновление - На пол года'),
        ),
        migrations.AddField(
            model_name='research',
            name='M_OM_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ежемесячное обновление - На один месяц'),
        ),
        migrations.AddField(
            model_name='research',
            name='M_OQ_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ежемесячное обновление - На один квартал'),
        ),
        migrations.AddField(
            model_name='research',
            name='M_OY_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ежемесячное обновление - На один год'),
        ),
        migrations.AddField(
            model_name='research',
            name='Q_HY_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ежеквартальное обновление - На пол года'),
        ),
        migrations.AddField(
            model_name='research',
            name='Q_OM_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ежеквартальное обновление - На один месяц'),
        ),
        migrations.AddField(
            model_name='research',
            name='Q_OQ_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ежеквартальное обновление - На один квартал'),
        ),
        migrations.AddField(
            model_name='research',
            name='Q_OY_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ежеквартальное обновление - На один год'),
        ),
        migrations.AddField(
            model_name='research',
            name='Stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='research',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='research',
            name='nominal',
            field=models.IntegerField(default=1, verbose_name='Номинальная цена'),
        ),
    ]
