# Generated by Django 2.2.5 on 2019-10-30 13:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20191029_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='contents',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Структура исследования'),
        ),
    ]
