# Generated by Django 2.2.5 on 2019-11-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20191031_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='extra',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AddField(
            model_name='research',
            name='extra_red',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительно*'),
        ),
    ]
