# Generated by Django 2.2.5 on 2019-11-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20191115_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='extra',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='research',
            name='extra_red',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='Дополнительно*'),
        ),
    ]
