# Generated by Django 2.2.5 on 2019-12-05 14:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20191115_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='data_update',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Обновление данных'),
        ),
        migrations.AlterField(
            model_name='research',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание исследования'),
        ),
        migrations.AlterField(
            model_name='research',
            name='target',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Цель исследования'),
        ),
    ]
