# Generated by Django 2.2.5 on 2020-02-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200103_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='Q_OM_cost',
        ),
    ]
