# Generated by Django 2.2.5 on 2020-04-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_research_q_om_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
