# Generated by Django 2.2.5 on 2020-04-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_research_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
