# Generated by Django 2.2.5 on 2020-04-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200401_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='date_update',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
