# Generated by Django 2.2.5 on 2020-04-01 04:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20200401_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='date_update',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 1, 4, 42, 49, 12757, tzinfo=utc), null=True),
        ),
    ]
