# Generated by Django 2.2.5 on 2020-05-29 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200401_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='date_update_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='date_update',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 29, 0, 39, 29, 182957, tzinfo=utc), null=True),
        ),
    ]
