# Generated by Django 2.2.5 on 2020-05-29 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200529_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='date_update_data',
        ),
        migrations.AlterField(
            model_name='research',
            name='date_update',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 29, 0, 40, 27, 256326, tzinfo=utc), null=True),
        ),
    ]
