# Generated by Django 2.2.5 on 2020-05-31 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20200529_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='date_update',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
