# Generated by Django 2.2.5 on 2020-05-31 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20200531_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='date_update',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
