# Generated by Django 2.2.5 on 2020-05-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20200531_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='date_new',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
