# Generated by Django 2.2.5 on 2020-05-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_research_date_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='date_new',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
