# Generated by Django 2.2.5 on 2020-05-31 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20200531_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='date_new',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
