# Generated by Django 2.2.5 on 2020-05-31 23:47

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20200531_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='date_new',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 31, 23, 47, 11, 283950, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='date_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
