# Generated by Django 2.2.5 on 2020-05-31 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20200531_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='date_new',
        ),
    ]
